In [1]:
import re
import pandas as pd

In [2]:
df = pd.read_csv("../crawling/merged_csv.csv")

In [3]:
print(df.shape)
df.head()

(11101, 5)

,Unnamed: 0,Unnamed: 0.1,category,header,content
0,0,0,politics,Mary Trump slams Susan Sarandon as a 'moron' f...,Mary Trump criticized longtime activist and ac...
1,1,1,politics,Moment two Ukrainian fighter jets bomb Russian...,New footage shows the moment that Ukrainian A...
2,2,2,politics,Mark Esper on what's at stake if Donald Trump ...,Former Secretary of Defense Mark Esper was con...
3,3,3,politics,Hunter Biden enlists Hollywood mega-lawyer for...,Hunter Biden has garnered quiet support and fi...
4,4,4,politics,President Trump's response to Mark Esper's 60 ...,When asked for comment on this week's intervie...

In [4]:
df.drop(columns="Unnamed: 0", axis=1, inplace=True)
df.drop(columns="Unnamed: 0.1", axis=1, inplace=True)

In [5]:
df

,category,header,content
0,politics,Mary Trump slams Susan Sarandon as a 'moron' f...,Mary Trump criticized longtime activist and ac...
1,politics,Moment two Ukrainian fighter jets bomb Russian...,New footage shows the moment that Ukrainian A...
2,politics,Mark Esper on what's at stake if Donald Trump ...,Former Secretary of Defense Mark Esper was con...
3,politics,Hunter Biden enlists Hollywood mega-lawyer for...,Hunter Biden has garnered quiet support and fi...
4,politics,President Trump's response to Mark Esper's 60 ...,When asked for comment on this week's intervie...
...,...,...,...
11096,food,Classic Tater Tot Casserole with Green Beans,This is one of my favorite childhood recipe's....
11097,food,Stews of South India,Know about different stews present in South In...
11098,food,Biscuits from Self Rising Flour,Biscuits are a learning experience. Best buy e...
11099,food,Streusel Topping for Banana Bread for Example,Banana bread topping is added just before you ...
11100,food,3 Fresh Summer Drinks That Refresh You,"If you are looking for colorful, fresh, floral..."

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11101 entries, 0 to 11100
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  11101 non-null  object
 1   header    11101 non-null  object
 2   content   9499 non-null   object
dtypes: object(3)
memory usage: 260.3+ KB

In [7]:
df[df['content'].isna()]

         category                                             header content
211    technology                Technology to Make Your Life Easier     NaN
214    technology          Steps to Automating Your Production Plant     NaN
240    technology             How to Cancel a Subscription on iPhone     NaN
243    technology       What Tools Are Needed for 5G mmWave Testing?     NaN
246    technology     TRXmining : The Next Decentralized Finance Hub     NaN
...           ...                                                ...     ...
11052        food                      Kung Pao Chicken Introduction     NaN
11053        food  One of the Most Popular Snack and Dessert Tofu...     NaN
11054        food           Traditional Chinese Snack -- Stinky Tofu     NaN
11093        food                            No Flour Chocolate Cake     NaN
11094        food                       Four Cheese Macaroni - Pasta     NaN

[1602 rows x 3 columns]

In [8]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9499 entries, 0 to 11100
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  9499 non-null   object
 1   header    9499 non-null   object
 2   content   9499 non-null   object
dtypes: object(3)
memory usage: 296.8+ KB

In [9]:
#pd.set_option('display.max_rows', None)
df[df.duplicated() == True]

,category,header,content
753,technology,Motivational Sayings Great Ones,Why examine motivational sayings? For motivati...
754,technology,5 Reasons Why the Fire TV Stick 4k Is the Top ...,The Fire TV Stick 4K has quickly become the to...
755,technology,The Anker PowerConf H700 AI-Powered Wireless H...,A headset that mitigates noise and lets you ta...
756,technology,Four Gadgets that will Enhance Your Cycling Ex...,"Friends, through this article of today, we are..."
757,technology,Headphones On and World Off With Happy Plugs A...,The Happy Plugs Air 1 ANC True Wireless Earbud...
...,...,...,...
11088,food,"When Life Gives You Lemons, Reap Their Health ...",From preventing heart disease and cancer to im...
11089,food,Poi Besar (Malabar spinach mustard curry / Bas...,"The end of spring and beginning of summer, the..."
11090,food,Matar Paneer - Indian Cuisine,Matar Paneer - In Hindi Matar means Green peas...
11091,food,What Is Structured Water and How to Prepare it...,"Learn what structured water is, how to make it..."
11092,food,Moroccan Dry Plum Tagine,Delicious and super easy Moroccan tagine

In [10]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6710 entries, 0 to 11100
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  6710 non-null   object
 1   header    6710 non-null   object
 2   content   6710 non-null   object
dtypes: object(3)
memory usage: 209.7+ KB

In [11]:
# Remove numbers
for i, row in df.iterrows():    
    row["content"] = re.sub(r'\d','', row["content"])
    row["header"] = re.sub(r'\d','', row["header"])
    
df

,category,header,content
0,politics,Mary Trump slams Susan Sarandon as a 'moron' f...,Mary Trump criticized longtime activist and ac...
1,politics,Moment two Ukrainian fighter jets bomb Russian...,New footage shows the moment that Ukrainian A...
2,politics,Mark Esper on what's at stake if Donald Trump ...,Former Secretary of Defense Mark Esper was con...
3,politics,Hunter Biden enlists Hollywood mega-lawyer for...,Hunter Biden has garnered quiet support and fi...
4,politics,President Trump's response to Mark Esper's Mi...,When asked for comment on this week's intervie...
...,...,...,...
11096,food,Classic Tater Tot Casserole with Green Beans,This is one of my favorite childhood recipe's....
11097,food,Stews of South India,Know about different stews present in South In...
11098,food,Biscuits from Self Rising Flour,Biscuits are a learning experience. Best buy e...
11099,food,Streusel Topping for Banana Bread for Example,Banana bread topping is added just before you ...
11100,food,Fresh Summer Drinks That Refresh You,"If you are looking for colorful, fresh, floral..."

In [12]:
from langdetect import detect

wrong_languages = ["ko", "hi", "ml", "ru"]

for i, row in df.iterrows():
    try:           
        content_language = detect(row["content"])
        if content_language in wrong_languages:
            df.drop(i, inplace=True)
            print()
            print(f"!!! Detect content as {content_language} language.\nDrop row form df:\n{row}")
            print()
            
            df.drop(i, inplace=True)        
            
    except Exception as error:
        print(f"Drop row form df:\n {row}")
        df.drop(i, inplace=True)

(6710, 3)
Detect content as no language.
Drop row form df:
category                                   technology
header      Emails - Deleting from Gmail - One Method
content            I have to start deleting emails...
Name: 376, dtype: object

-----------------------------

Detect content as sv language.
Drop row form df:
category                                           technology
header      Photos - Transferring from DVD to Hard Drive -...
content                          Installing photos from disk.
Name: 682, dtype: object

-----------------------------

Detect content as pt language.
Drop row form df:
category                                              science
header                                           Quem sou eu?
content     Além da aspirante a poeta que já publicou dive...
Name: 1322, dtype: object

-----------------------------

Detect content as ca language.
Drop row form df:
category                       science
header      Physics: The Heat Capacity
content               An experiment —
Name: 1347, dtype: object

-----------------------------


!!! Detect content as hi language.
Drop row form df:
category                                              science
header      Tissue In Hindi Science Class th Chapter  | ऊत...
content     अगर आप  वी विज्ञान (th Science) के छात्र है तो...
Name: 1373, dtype: object

Detect content as es language.
Drop row form df:
category                                             business
header      ¿Crees que sabes hablar con tus (potenciales) ...
content     “Hola, ¿cómo estás? Quería hablarte de mi proy...
Name: 1495, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                                             business
header      Petit guide de survie pour hypersensibles en m...
content     Dédicace à tou(te)s les fragiles. J’ai découve...
Name: 1548, dtype: object

-----------------------------


!!! Detect content as ko language.
Drop row form df:
category                                             business
header                                 遇到疫情風暴 喜多方拉麵透過網路會員度過危機
content     隨著疫情持續延燒兩年，日本許多中小企業已經紛紛不支倒地，其中餐飲業受到的衝擊最大。根據日本中...
Name: 1549, dtype: object


!!! Detect content as ko language.
Drop row form df:
category                                                 food
header                                                   山東小吃
content     下｜春季私房菜 把在地設計成一道菜，親自研發料理 來自陶主廚的話：\r\n「每一道菜都經歷失...
Name: 1710, dtype: object

Detect content as id language.
Drop row form df:
category                             food
header      Peanut Butter, You’re My Jam!
content                 I luv yuh, man —
Name: 1785, dtype: object

-----------------------------

Detect content as es language.
Drop row form df:
category                                                 food
header                                              Un tubito
content     La cena del . La de Nochevieja. Beber entre se...
Name: 1790, dtype: object

-----------------------------

Detect content as no language.
Drop row form df:
category                                           technology
header                            <ForrigeUke uke=”" år=”" />
content     Dette var uken for en sniktitt inn i fremtiden...
Name: 1838, dtype: object

-----------------------------


!!! Detect content as ko language.
Drop row form df:
category                                             business
header                                 社會新鮮人習慣使用手機 卻不知道怎麼操作電腦
content     上個世紀末剛進入新聞圈的時候，台灣正好遇到廣播電視頻道開放，百家爭鳴。許多過去在報社的記者們...
Name: 1936, dtype: object


!!! Detect content as ko language.
Drop row form df:
category                                             business
header          #商業【Dear商家，Omicron疫情間你該檢視的個重點】｜RULES CREATIVE
content     Dear 商家， 疫情再起，不知你的生意是否受到影響？ 如果沒有，那太好了；如果有，也請安下...
Name: 1985, dtype: object


!!! Detect content as ml language.
Drop row form df:
category                                        entertainment
header                    Djinn Malayalam movie Soubin Shahir
content     സൗബിന്‍ ഷാഹിറിനെ നായകനാക്കി സിദ്ധാര്‍ഥ് ഭരതന്‍...
Name: 2210, dtype: object


!!! Detect content as ml language.
Drop row form df:
category                                        entertainment
header                 Kavya Madhavan May Be Questioned Today
content     നടിയെ തട്ടിക്കൊണ്ടുപോയി പീഡിപ്പിച്ചെന്ന കേസിന്...
Name: 2212, dtype: object

Detect content as fr language.
Drop row form df:
category                              entertainment
header      The Unbearable Weight of Massive Talent
content                                Cage Rampage
Name: 2228, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                                    entertainment
header      Strange Sexual Preferences of Gundam Villains
content        At some point, Gundam villains are creeps.
Name: 2235, dtype: object

-----------------------------

Detect content as ca language.
Drop row form df:
category                                entertainment
header                Top  Episodes From Supernatural
content     Here are Top  episodes from Supernatural!
Name: 2253, dtype: object

-----------------------------

Detect content as da language.
Drop row form df:
category                                        entertainment
header        Uplifting Funeral Songs for Older Generation ()
content     funeral songs for older generation\r\nmodern f...
Name: 2568, dtype: object

-----------------------------

Detect content as et language.
Drop row form df:
category                                        entertainment
header              Top  Japanese Anime Series of All Time ()
content     japanese anime series\r\njapanese anime websit...
Name: 2572, dtype: object

-----------------------------

Detect content as af language.
Drop row form df:
category                                        entertainment
header                             Top  Best Dubstep Songs ()
content     skrillex best dubstep songs\r\nbest dubstep so...
Name: 2592, dtype: object

-----------------------------

Detect content as lv language.
Drop row form df:
category                                        entertainment
header                Top  Best Punjabi Movies of All Time ()
content     comedy punjabi movies\r\npunjabi movies \r\nne...
Name: 2624, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                                        entertainment
header               Top  Best Portuguese Movies Ever Made ()
content     portuguese movie \r\nportugal movies list\r\nf...
Name: 2627, dtype: object

-----------------------------

Detect content as et language.
Drop row form df:
category                                        entertainment
header                 Top  Best Telugu Movies of All Time ()
content     telugu movies \r\ntelugu new movies\r\ntelugu ...
Name: 2630, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                                        entertainment
header                  Top  Best Vampire Movies Ever Made ()
content     vampire romance movies\r\nvampire movies list\...
Name: 2631, dtype: object

-----------------------------

Detect content as af language.
Drop row form df:
category                                        entertainment
header                   Top  Best German Movies Ever Made ()
content     german movies on netflix\r\ngerman movies list...
Name: 2642, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                                        entertainment
header                    Top  Best Dance Movies Ever Made ()
content     dance movies hollywood\r\ndance movies bollywo...
Name: 2646, dtype: object

-----------------------------

Drop row form df:
 category               entertainment
header      Film Review - Lost Kings
content         https://bit.ly/UrzpL
Name: 2706, dtype: object
Detect content as af language.
Drop row form df:
category                                        entertainment
header          Top  Best Indie Movies Of All Time ( Netflix)
content     best indie movies\r\nenglish indie movies\r\nn...
Name: 3236, dtype: object

-----------------------------

Detect content as nl language.
Drop row form df:
category                                        entertainment
header                       Top  Best Revenge Movies Ever ()
content     brutal revenge movies\r\nlatest revenge movies...
Name: 3244, dtype: object

-----------------------------

Detect content as nl language.
Drop row form df:
category                                        entertainment
header                   Top  Best Zombie Movies Ever ( List)
content     best zombie movies on netflix\r\ntop  zombie m...
Name: 3252, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                                        entertainment
header       Photos That Were Either Captured In A Dream, ...
content             Sometimes it's best not to ask questions.
Name: 3546, dtype: object

-----------------------------


!!! Detect content as ko language.
Drop row form df:
category                                              science
header                                             我們比黑猩猩還聰明﹖
content     Ben Ambridge《我們比黑猩猩還聰明﹖》，周沛郁譯，台北﹕天下文化， 書的內容其實不...
Name: 3778, dtype: object

Detect content as de language.
Drop row form df:
category                                          politics
header         Businesses Worried About Possible Lockdown.
content     is Wishy Washing Listening Or Even Being Fair?
Name: 4087, dtype: object

-----------------------------

Detect content as af language.
Drop row form df:
category                                             politics
header      Truss and Blinken: Supporting Ukraine Against ...
content                                            G Meeting.
Name: 4100, dtype: object

-----------------------------

Detect content as et language.
Drop row form df:
category                                           politics
header      Kamala Harris Temporarily Heads the White House
content                                 VP:  Kamala Harris.
Name: 4137, dtype: object

-----------------------------

Detect content as de language.
Drop row form df:
category                                        politics
header      Winter Not Likely to See Massive Covid Wave.
content            SAGE Adviser Professor Neil Ferguson.
Name: 4148, dtype: object

-----------------------------

Detect content as de language.
Drop row form df:
category                                             politics
header      Belarus President Lukashenko: Accused of Using...
content                            Polish-Belarussian Border.
Name: 4150, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                             politics
header      The Kings Fund: NHS on Its Knees.
content                       Under Pressure.
Name: 4159, dtype: object

-----------------------------

Detect content as ca language.
Drop row form df:
category                                             politics
header      Prince William Attacks Space Race and Space To...
content                                 Environmental Royals.
Name: 4225, dtype: object

-----------------------------


!!! Detect content as ru language.
Drop row form df:
category                                           technology
header      Razor Network стимулировала тестовую сеть, фаз...
content      миллион $RAZOR наград за тестирование. Команд...
Name: 5095, dtype: object

Detect content as tr language.
Drop row form df:
category                                           technology
header      Hissettiğin Kapanı Kim Çiziyor? Pozitiflerin D...
content     Zor bir toplantıda olduğumda, hayatımdaki tek ...
Name: 5109, dtype: object

-----------------------------

Detect content as pt language.
Drop row form df:
category                                           technology
header                             As Engrenagens da Inovação
content     Os fatores que geram a inovação, segundo a Ges...
Name: 5200, dtype: object

-----------------------------

Detect content as pt language.
Drop row form df:
category                                           technology
header      O que uma pessoa Quality Assurance Engineer fa...
content     Como uma profissional da área e que está na Bu...
Name: 5210, dtype: object

-----------------------------

Detect content as tr language.
Drop row form df:
category                                           technology
header                                  Teknoloji Podcastleri
content     Teknolojinin her geçen gün hayatımızın daha bü...
Name: 5212, dtype: object

-----------------------------

Detect content as tl language.
Drop row form df:
category                      food
header      Despise the Free Lunch
content           April , Day / —
Name: 5269, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                                        food
header      Why Did A-s-p-a-r-a-g-u-s Spell Success?
content                         Simple principles —
Name: 5333, dtype: object

-----------------------------

Detect content as ca language.
Drop row form df:
category                                                 food
header      It Took  Years for McDonald’s To Start Selling...
content                 Insane McDonald’s Trivia–Episode # —
Name: 5343, dtype: object

-----------------------------

Detect content as hr language.
Drop row form df:
category                                               sports
header      Kako učiti iz grešaka i unaprediti domaće pado...
content     Padobranstvo je sport koji je sve popularniji ...
Name: 6030, dtype: object

-----------------------------


!!! Detect content as ko language.
Drop row form df:
category                                               sports
header                                  Weekly Update # (KOR)
content     “NFT로 스포츠를 즐기자!” 안녕하세요 스포티움 커뮤니티 여러분, 우리 개발팀은 ...
Name: 6057, dtype: object

Detect content as fr language.
Drop row form df:
category                                             politics
header                        Le Manifeste du parti dégagiste
content     U n spectre hante le personnel politique en ex...
Name: 8497, dtype: object

-----------------------------


!!! Detect content as ru language.
Drop row form df:
category                                             politics
header                                 Liberation of Russians
content     «Партбилдинг» Вернемся к биографии звезды росс...
Name: 8507, dtype: object

Detect content as hr language.
Drop row form df:
category                                               sports
header      Kako učiti iz grešaka i unaprediti domaće pado...
content     Padobranstvo je sport koji je sve popularniji ...
Name: 8684, dtype: object

-----------------------------

Detect content as es language.
Drop row form df:
category                                               sports
header            IDEAS PARA HACER EL MUNDO DEL DEPORTE MEJOR
content     Si hoy fuera un chico de  años y me preguntara...
Name: 8692, dtype: object

-----------------------------

Detect content as fr language.
Drop row form df:
category                                               sports
header       IDÉES POUR RENDRE LA PRATIQUE SPORTIVE PLUS A...
content     Si j’étais un enfant aujourd’hui et que vous m...
Name: 8693, dtype: object

-----------------------------

Detect content as pt language.
Drop row form df:
category             weather
header      The Weather Vane
content            A poem —
Name: 9809, dtype: object

-----------------------------

Detect content as af language.
Drop row form df:
category                                             food
header              Strawberries Is Neccessory for Health
content     Advantages, and disadvantages of strawberries
Name: 10041, dtype: object

-----------------------------

Detect content as af language.
Drop row form df:
category                               food
header                      Herb Window Box
content     Box, jars, dirt, seeds, time...
Name: 10053, dtype: object

-----------------------------

Detect content as no language.
Drop row form df:
category                                                 food
header                             Top  Best Salad Spinner ()
content     oxo salad spinner\r\noxo steel salad spinner\r...
Name: 10073, dtype: object

-----------------------------

Detect content as de language.
Drop row form df:
category                                    food
header                    Egg - Poached in Water
content     Salt, water, egg. Simmer  minutes...
Name: 10287, dtype: object

-----------------------------

Detect content as af language.
Drop row form df:
category                                        food
header      Empanada - Making with Dinner Roll Dough
content          A filled, deep fried dinner roll...
Name: 10314, dtype: object

-----------------------------

Detect content as it language.
Drop row form df:
category                                             food
header                        Pecan Pie with Tuaca Brandy
content     Pecan pie, nutty, caramel, need I say more...
Name: 10323, dtype: object

-----------------------------

Detect content as tl language.
Drop row form df:
category                                                 food
header      Do Restaurants Allow Someone to Wash Dishes as...
content                                              Payback!
Name: 10363, dtype: object

-----------------------------

Detect content as ca language.
Drop row form df:
category                                    food
header      Salsa - a Five Minute Mrs. Wages Mix
content       Tomatoes, Mrs. Wages salsa mix....
Name: 10372, dtype: object

-----------------------------

Detect content as es language.
Drop row form df:
category                                                 food
header                                         Indian Recipes
content     Indian Recipes - Vegetable Pulao Recipe Indian...
Name: 10413, dtype: object

-----------------------------

Detect content as id language.
Drop row form df:
category                       food
header      Filled Krumkake Cookies
content     Using a Krumkake iron..
Name: 10442, dtype: object

-----------------------------

Detect content as af language.
Drop row form df:
category                                              food
header      Brussels Sprouts Sauteed with Corned Beef Hash
content                   Not a vegetarian dish, beware...
Name: 10444, dtype: object

-----------------------------

Detect content as ca language.
Drop row form df:
category                                  food
header      Yummy Custard Buns You Should Make
content        delicious homemade custard buns
Name: 10455, dtype: object

-----------------------------

Detect content as sv language.
Drop row form df:
category                            food
header       Ham, Macaroni and Pea Salad
content     My hubby's favorite salad...
Name: 10458, dtype: object

-----------------------------

Detect content as it language.
Drop row form df:
category                           food
header             Yummy Tuna Baguettes
content     delicious stuffed baguettes
Name: 10482, dtype: object

-----------------------------

Detect content as es language.
Drop row form df:
category                             food
header      Delicious Homemade Mortadella
content          Easy homemade mortadella
Name: 10513, dtype: object

-----------------------------

(6638, 3)

In [13]:
import re

pd.set_option('display.max_rows', None)
for i, row in df.iterrows():        
    row["content"] = row["content"].replace("\n"," ")
    row["content"] = row["content"].replace("\r"," ")
    row["content"] = re.sub(r'[^a-zA-Z\s]','', row["content"])

    row["header"] = row["header"].replace("\n"," ")
    row["header"] = row["header"].replace("\r"," ")        
    row["header"] = re.sub(r'[^a-zA-Z\s]','', row["header"])

In [14]:
#TODO: What to do?
df = df[df["content"].apply(len) > 20]